### ISSUE TITLE
[Bug Report] Spaces instead of Underscores in the Filename Preview

### ISSUE THREAD

**Issue by PraetorAugustus** [iquercorb/OpenModMan#100]
Super small bug, but it gets me every time.

**Current Behavior**
In the Mod-package editor when creating a new package, the Filename Preview doesn't transform spaces to underscores if the source folder doesn't have them.

OMM will (correctly) replace the spaces with underscores if I edit the Display Name, the Version, or Zip type.

![Screenshot 2024-07-12 185352](https://github.com/user-attachments/assets/ac2a043a-885a-4463-ae96-5922098b42eb)

**Expected Behavior**
Filename Preview should have underscores instead of spaces when the dialog first displays.

![Screenshot 2024-07-12 190019](https://github.com/user-attachments/assets/62aa37b7-3957-4a07-80b5-28cd7982e1e9)

It's easy to reproduce and happens every time, but let me know if you want more info.

Thanks.

**Comment by PraetorAugustus** [comment]
Gah! Sorry for the bare subject line. I forgot to include the nature of the bug.

**Comment by iquercorb** [comment]
Thanks for report, fixed in source code, will be corrected in the next release
