### ISSUE TITLE
Alpha testing of next build

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#101]
I can offer my help in testing the next release. So that it gets there with less problems or without in perfect total. Send me an alpha build of the next release when it is ready and the issue list. Also if you did any other non documented changes please explain logic of them.

**Comment by iquercorb** [comment]
You can test this build if you want:
[OpenModMan_1-3-0-x64_Portable.zip](https://github.com/user-attachments/files/16244073/OpenModMan_1-3-0-x64_Portable.zip)

**Comment by lmiol** [comment]
> You can test this build if you want:
> 
> https://github.com/iquercorb/OpenModMan/releases/tag/1.3b

What exactly I should test?
Links of issues?

**Comment by PraetorAugustus** [comment]
Alpha build is good so far. I haven't found anything major.

@lmiol ?

**Comment by lmiol** [comment]
> Beta build is good so far. I haven't found anything major.
> 
> @lmiol ?

I found one thing, later describe

**Comment by iquercorb** [comment]
Do you finally have something to report, or can I publish the new release ?

**Comment by lmiol** [comment]
> Do you finally have something to report, or can I publish the new release ?

https://github.com/iquercorb/OpenModMan/issues/103

**Comment by lmiol** [comment]
Right now I investigating one more with repo downloading.
I need 3-4h to finish test cases

**Comment by lmiol** [comment]
https://github.com/iquercorb/OpenModMan/issues/104
i am finished
