### ISSUE TITLE
[BUG] Fast switch between overlap mods not have enough time to delete previous mod

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#103]
https://github.com/user-attachments/assets/4522744f-7ae4-4e0b-b368-c68765337dc6

i think here Install Button (and double click) on other overlap mods should be inactive until first mod will be installed
but for other mods without overlap Install button  (and double click)  should work fine, because we should have avaibility to instal separatly

on video its works fine because i need to click to small mod file of 2mb, if it would be greater it would work without fast click

**Comment by iquercorb** [comment]
Due to how Mod operations are queued and processed, correcting this behaviour require quite massive code refactoring... In the absolute, such situation should be rare in common usage situation.
