### ISSUE TITLE
[BUG/Wrong Logic] Open in Explorer do opening file instead of explorer folder

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#104]
1 being in local library
2 click right button on mod
3 click **Open in Explorer...**
![image](https://github.com/user-attachments/assets/4685531b-75e7-462e-9ef2-4b8d6e347ad9)

**Actual result:** File opening in program (Winrar for example)
**Expected result:** 
OR opening folder where file locates (because name **Open in Explorer...**)
OR name of menu should be named **Open file...**

explanation: in many apps **open in explorer** and **show in explorer** are the same action - Open folder with file

**Comment by iquercorb** [comment]
That was in purpose, but at this time it was assumed that packages were all standard zip (which can be viewed in explorer), but this is no longer the case. So I will change the logic.

**Comment by lmiol** [comment]
I mean there should be 2 actions
Open file
Oprn location
Both is very usefull
I mean Open in explorer (but rename into Open file)
And Open location
Both helpfull

**Comment by iquercorb** [comment]
This is not that simple, you forgot that Mod might also be raw folders... in this case there si not "file" to open, also, the "explore" and "open" shell commands act differently depending user system configuration...

**Comment by lmiol** [comment]
> This is not that simple, you forgot that Mod might also be raw folders... in this case there si not "file" to open, also, the "explore" and "open" shell commands act differently depending user system configuration...

Okay don't remove current action "Open in Explorer" what you did

**Comment by iquercorb** [comment]
Ok back to previous logic but changed menu logic to display "open in explorer" or "open with default program" depending Mod is a folder or file. I will not add "Open Location" menu item since all mods of a library are located in the same folder, this is nonsens in context, and especially in case of multiple selection.
