### ISSUE TITLE
[Suggestion] Tooltip for each icon

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#105]
![image](https://github.com/user-attachments/assets/e0781f66-b8b2-4516-b5fb-204da2c77860)
i think here is should be explanation what icons mean on hover
For Local Library and for Network Library

i still don't know what this sun is mean
sun shows for both mods but after instalation one of them - the second mod changed sun to download icon. i dont understand why
![image](https://github.com/user-attachments/assets/de4aade6-a01a-4a82-b85a-5a2168657928)

BTW here is already exist some tooltip but not for icons
![image](https://github.com/user-attachments/assets/f7c084f6-e841-4733-bf60-94e843072c59)

**Comment by iquercorb** [comment]
Implemented tooltips for status icons, also removed "New" status icon which were confusing and useless.
