### ISSUE TITLE
[Suggestion] Show in bytes button

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#106]
when i do updates for mods i need to update repo file
so i am not use Repo Editor, i am just opening my RAW file and changing few fields
ident, file, xxhsum, bytes
xxsum i getting from Properties from local library (because mod updating by me here for testing)
and want to get also get bytes, but it is on KB unfortunatly

could you do button **Show in bytes**?
![image](https://github.com/user-attachments/assets/3804e491-0c4c-4c7d-82a5-3748ee16c16c)

**Comment by iquercorb** [comment]
With this suggestion and the other one about CRLF in Mod Description, I suspect that you are currently struggling modifying and updating Mods and seek for some automation in the process.

Did you know OMM have some not exposed features that help Mod designers into their tasks ? 
- First, you can leave your Mod as folder within the Library folder, this allow you to directly modify files then try and check by installing/removing it to the game.
- Such "developement" folder supports Description and Picture, what you have to do is to put description text file and picture in the Library folder, along the Mod folder, and naming them the same as folder "core" name...
For example, if you have Mod folder nammed "My_Great_Mod_v1.2", you name the description file "My_Great_Mod.txt" and the picture "My_Great_Mod.png". Description and pictures are (if everything work file) automatically updated once you modify it from an external program.
Whith all that, if you right click on the Mod folder to "Edit in Modpack Editor", the Descriptions and Pictures fields are automatically filled.

**Comment by lmiol** [comment]
how exactly this icon works (could you tell all scenarios)
![image](https://github.com/user-attachments/assets/e57a9806-5771-4dcd-8716-39ba0d241232)

**Comment by lmiol** [comment]
> With this suggestion and the other one about CRLF in Mod Description, I suspect that you are currently struggling modifying and updating Mods and seek for some automation in the process.
> 
> Did you know OMM have some not exposed features that help Mod designers into their tasks ?
> 
> * First, you can leave your Mod as folder within the Library folder, this allow you to directly modify files then try and check by installing/removing it to the game.
> * Such "developement" folder supports Description and Picture, what you have to do is to put description text file and picture in the Library folder, along the Mod folder, and naming them the same as folder "core" name...
>   For example, if you have Mod folder nammed "My_Great_Mod_v1.2", you name the description file "My_Great_Mod.txt" and the picture "My_Great_Mod.png". Description and pictures are (if everything work file) automatically updated once you modify it from an external program.
> * With all that, if you right click on the Mod folder (within OMM) to "Open in Modpack Editor...", the Description and Picture fields are automatically filled, you just have to save as Modpack file.

thx. i found out about folder but nothing else. its usefull for me

**Comment by lmiol** [comment]
also could you tell what method you use for xxhum?

**Comment by iquercorb** [comment]
> How exactly the icon "Update" works Could you tell all scenarios?

The icon indicate this mod is already present in local library as a lower version. Behavior depend on Channel parameters. The default behavior is: Once the new version is downloaded, the old version Mod is renamed or deleted (so it disappear from local Library) after being uninstalled if required... If my memory is good, in case the old version Mod was found installed, the new version is automatically installed at the end of process, replacing the old version.

**Comment by lmiol** [comment]
> > How exactly the icon "Update" works Could you tell all scenarios?
> 
> The icon indicate this mod is already present in local library as a lower version. Behavior depend on Channel parameters. The default behavior is: Once the new version is downloaded, the old version Mod is renamed or deleted (so it disappear from local Library) after being uninstalled if required... If my memory is good, in case the old version Mod was found installed, the new version is automatically installed at the end of process, replacing the old version.
how exactly works connection of mod? same same of ident but before version?
i mean 
tomorrowland_vegas_v1.15
tomorrowland_begas_vtest
both will be the same 

and what SUN (or Star) icon meaning?

**Comment by lmiol** [comment]
i tried xxhsum.exe and i got not same value as yours
it seems you using some hash
could you tell how exactly?

**Comment by iquercorb** [comment]
> how exactly works connection of mod? same `<mod ident>` name but before postfix of _v*?

Yes. Internally this is stored as the "core" name.

`File string: My_Cool_Great_Mod_v2.0.ozp`
`Iden string: My_Cool_Great_Mod_v2.0`
`Core string: My_Cool_Great_Mod`

> and what SUN (or Star) icon meaning? sometime i can see Download icon and almost everytime is SUN

This mean "New", it indicates no version or this Mod in the local library...

And if you ask for: 
Grey down arrow : Mean "Downgrade", there is already a greater version of the Mod in the local library
Triangle/Warning : Mean "Missing dependency", the Mod dependencies cannot be satisfied, one or more dependency Mod are not available in current (checked) network repositories. It is up to the repository manager to make it available.

**Comment by lmiol** [comment]
> Grey down arrow : Mean "Downgrade", there is already a greater version of the Mod in the local library
downgrade is not obvious icon, misunderstanding with simple download
i think its fine icons now, but i think app is exctremly need Tooltip for icons.
Without your explanation i would never found out what suns means and gray downgrade.

Dont decide right now about icons (if you already want to)
I will do few designs for you for icons and upload you later.
1 Sun: New mod (not installed)
2 Down arrow with square brackets: Downloading in progress 
3 Down arrow: Downgrade to old version
4 Up arrowL Upgrade to new version
5 Cross: Error of mismatch data/failed link or else
5 Triangle/Warning: Missing dependency
 i missed something?

**Comment by lmiol** [comment]
also could you tell algorythm of encryption of repo file <description> section?
  <description bytes="135">data:application/octet-stream;base64,eJwdzDEKwjAYBlBni3f4oIsGTVqHgt1EcHHQxUlEYhuSYNI/JJEsHl70HeDVNU520gkXmRI2OMiUncJiztg5Wm0n6bB/Z0OxZwzOW3L44GbIqyC1ui9NziH1QpRS+NN4GhMfyItt0+5E04nh/z3ajpvs3api7EjxhWsYZVa/EmtUmH0Bfbkp8Q==</description>

**Comment by iquercorb** [comment]
It is not encrypted, it is compressed using standard Deflate algorithm

**Comment by lmiol** [comment]
> It is not encrypted, it is compressed using standard Deflate algorithm

i tried openssl to decrypt with base64 and nothing

**Comment by iquercorb** [comment]
> i tried openssl to decode with base64 and nothing

The binary data is encoded in base64 to be included in the data URI, but the binary data itself is compressed raw text using Deflate aka Gzip compression (implemented in Zlib) which is the legacy compression method used by Zip file format.

Process for writing:
`Raw text => Gzip Compress => Base64 encode`

Process for reading:
`Base64 decode => Gzip Decompress => Raw text`

The Deflate algorithm is very common, usually implemented from the open source Zlib library, it is available in standard in Python and PHP for example... Using PoweShell it seem you can use GzipStream class to perform Decompression. 

[https://stackoverflow.com/a/46814816
https://gist.github.com/marcgeld/bfacfd8d70b34fdf1db0022508b02aca](https://sphinx.graae.dk/pages/gzipcompressionandbase64encoding/)

Or you may use Gzip for Windows:

https://gnuwin32.sourceforge.net/packages/gzip.htm
https://www.gnu.org/software/gzip/manual/gzip.html#Invoking-gzip

**Comment by lmiol** [comment]
Raw text is a string or file?

**Comment by iquercorb** [comment]
A string... but this is nearly the same, a text file is simply a string saved in hard drive (indexed as a file in the file system)... everything is an octet/byte stream in computing, raw text, picture or executable, it is how you read and process it that make it something.

**Comment by lmiol** [comment]
thanks

**Comment by iquercorb** [comment]
Added raw bytes values within parentheses next to the human readable size.

**Comment by lmiol** [comment]
> I will do few designs for you for icons and upload you later.
As i promised
Same color but different ways of arrow
![image](https://github.com/user-attachments/assets/409615f9-730b-4d14-b50e-04f843c821fb)

Same icon of double arrows, but different colors Blue - is upgrade and orange downgrade 
![image](https://github.com/user-attachments/assets/9be0fa2d-6c7f-47c8-9fee-659c8aab877d)
![image](https://github.com/user-attachments/assets/be6aa218-2e48-4854-8253-72cd3c582b48)

also on all pictures is litle bit resized Pause button dimensions

Red/Orange are always negative actions
Blue/Green are positive ones
 First image looks cool, but we must understand that downgrade is a not a often case. Upgrade is often case. So always to see Orange uparrow is littlebit confuse for person.
So if they all the time will se same icon but with different colors it would more userfriendly. Like this one example when they see upgrade as ofthen case
![image](https://github.com/user-attachments/assets/e822566a-666d-4a7d-850e-e1463a789bba)
