### ISSUE TITLE
[Suggestion] Change symbol of line break for description in modpack.xml

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#108]
I decided to automatically create the package.xml file using a simple solution in BATCH.

```
@echo off
set category=MAP
set "description=## Name1"
set "description1=**blabla:** blabla [homepage](https://blabla)"  
set "description2=**blabla2:** blabla [forkpage](https://blabla2)"
set description3=**blabla date:** 1 Dec, 2023
set thumbnail=codeforbase64 (nevermind this)

echo ^<?xml version="1.0"?^> > modpack.xml
echo ^<Open_Mod_Manager_Package^> >> modpack.xml
echo ^<install^>%install%^</install^> >> modpack.xml
echo ^<category^>%category%^</category^> >> modpack.xml
echo ^<description^>%description%^ >> modpack.xml
echo %description1% >> modpack.xml
echo %description2% >> modpack.xml
echo %description3% ^</description^> >> modpack.xml
echo 	^<thumbnail^>%thumbnail%^</thumbnail^> >> modpack.xml
echo ^</Open_Mod_Manager_Package^> >> modpack.xml
```

after generation it looks like modpack.xml what created from Mod-package editor from OMM
buttttttttttttttttttttttttt....
my genereated modpack.xml lools like this in preview
![image](https://github.com/user-attachments/assets/9e37bf1a-faa1-4ec8-ba48-3ffd6d3b7bcc)

but expected like this (this screen made after created file from  Mod-package editor from OMM)
![image](https://github.com/user-attachments/assets/fff018a2-3aee-480e-8439-fbb951268e34)

I did investigate and find out My symbol of line break (what created by echo) is not the same as yours.

I tried a lot of variants and I think its not possible to do right line break symbol as yours via BATCH

Could you do recognizing of your symbol of line break kinda **\r\n** for example?

Also xml doesn't support line breakes inside tag (its only 1 line). so it seems is only one solution to fix this - is  to make **\r\n** support
and if someone want to write \r or \n in description - you can save as `\\r \\n` and read as \r \n in preview
there is no conflict

**Comment by iquercorb** [comment]
Actually, the supported new line sequence in Mod descriptions is CRLF ( `\r\n` or `0D 0A` ASCII sequence) which is the Windows standard, and this is saved as this (with CRLF) in the XML file. 
You problem is, I think, that the BATCH ECHO command generate a single LF ('\n', 0A'). You'd better use PowerShell which allow more sophisticated string manipulation.

**Comment by lmiol** [comment]
> Actually, the supported new line sequence in Mod descriptions is CRLF ( `\r\n` or `0D 0A` ASCII sequence) which is the Windows standard, and this is saved as this (with CRLF) in the XML file. You problem is, I think, that the BATCH ECHO command generate a single LF ('\n', 0A'). You'd better use PowerShell which allow more sophisticated string manipulation.

line break character not supported by xml format (doesnt matter ascii or utf8)
it should be `<description> some text \r\n new line text </description> `
instead of a symbol which any editor do it like a line break.
i tried
notepad.exe
notepad++.exe
sublime.exe
akelpad.exe
wordpad.exe

i mean if someone to try to generate xml by any method he doesn't need to investigate how to support right character of line break for open mod manager in his xml

And by the way. ASCII is old Americal standard bounded old programs with only english characters.
Even new Sublime Text doesn't it support by default.
UTF-8 is common

**Comment by lmiol** [comment]
I don't deny that I'm pursuing my goal and it benefits me if you do it this way. 
But that doesn't negate the fact that it's the right thing to do and that it will be convenient for everyone who wants to create XML descriptions themselves.
But I won't insist. I'll figure out how to insert line breaks with CRLF.

**Comment by iquercorb** [comment]
> line break character not supported by xml format (doesnt matter ascii or utf8) it should be `<description> some text \r\n new line text </description> ` instead of a symbol which any editor do it like a line break. i tried notepad.exe notepad++.exe sublime.exe akelpad.exe wordpad.exe

I understand what you are asking for now. But, you are wrong, the only characters that must be escaped within XML text nodes are `<> &`. Furthermore "\r" or "\n" are not valid XML escape sequences... however you could use the `&#xD;&#xA;` to insert CRLF sequence as escaped ASCII code, the parser should properly decode it... try it.

> i mean if someone to try to generate xml by any method he doesn't need to investigate how to support right character of line break for open mod manager in his xml

There is no investigation... CRLF is the Windows standard, and this can be put within the XML text node as this, without escaping...

> And by the way. ASCII is old Americal standard bounded old programs with only english characters. Even new Sublime Text doesn't it support by default. UTF-8 is common

The parser is UTF-8 standard, it encode and decode UTF-8, to/From Windows UTF-16... CR ( 0D ) and LF ( 0A ) are ASCII basic codes that are shared by UTF-8 and almost all known and used code pages.

**Comment by lmiol** [comment]
> &#xD;&#xA

single &#xB is fixed broblem

**Comment by iquercorb** [comment]
> single `&#xB;` is fixed broblem

`0b` is code for vertical tabulation... glad to know it works (I don't know how) however I recommend to use `0d 0a` which is the proper sequence for new line...
