### ISSUE TITLE
[Bug/Wrong Logic] Installed mod from different channels doesn't have overlap function

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#111]
First my channel
Target folder **C:\Game**
Mod library C:\Mods Test\
i have mod1 with file **1.jpg**

Second my channel
Target folder **C:\Game**
Mods Library C:\Mods Final\
i have mod2 with file **1.jpg**

Steps to reproduce
1 install mod1
2 install mod2
AR: Both installed with green checkmark
ER: Second mod should be overlap previous because target folder the same
It doesnt matter from what channel it installed because it conflicts with previous mod

**app 1.3.8**

**Comment by iquercorb** [comment]
This si not a bug, this is a known limitation, overlapping management work only within the same channel. It is assumed user know what he do.

**Comment by lmiol** [comment]
It's not obvious. So if I install mod - second mod will do backup files of installed first mod :)

**Comment by iquercorb** [comment]
Yes, you are not supposed to have two (or more) channels pointing the same target directory, if you do so, it is at your own risks.
