### ISSUE TITLE
Upgrading mod from network doesn't update presets

### ISSUE THREAD

**Issue by fizzle77** [iquercorb/OpenModMan#112]
When upgrading a package by downloading it from a network repository, the previous version is correctly superseded but you have to manually update all presets that included the old version. The old version no longer appears there, but the new version has to be manually added.

Seeing this in version 1.3 but I don't think this has ever worked.

**Comment by lmiol** [comment]
idk will understand the author of project, but for me not enough data for steps of reproduce.
all what I can say -- name of the version should be right to Upgrade or Downgrade the mods while updating files

**Comment by iquercorb** [comment]
Fixed in source code... this is currently implemented but modification of presets are not properly saved... I took the opportunity to refactor some code.
