### ISSUE TITLE
Uninstall Error conflict

### ISSUE THREAD

**Issue by Snacko** [iquercorb/OpenModMan#114]
Ok, so I've been using OvGME for years, and yesterday it had an error removing a mod. I had tried to uninstall it while DCS was running, and the file was locked.  Ok, no biggie....   I'll just go to the Backup folder and restore the original manually.

But it's not there!  There is nothing in the Backup folder!?  The original was gone...
So, I looked at the log and it showed the error, and after the error it said cleanup or something..

I think that after it failed to uninstall the mod, and failed to overwrite the mod file with the backup, ....   
**it went ahead and cleaned up.. and deleted the original!!**

So, after restoring the DCS game to get the original file back, I installed Open Mod Manager.  Which did the same thing just now!

**  If it gets any Error when restoring the original files it should not delete them!  **

**Comment by iquercorb** [comment]
Changed restoration logic to prevent backup data to be deleted in case of error during data restoration, will be active in the next release.
