### ISSUE TITLE
[Bug] Repository Description is disappeared after link load

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#115]
Preconditions: Repository link already added, Link has a descroption (example     <repository base="https://pastebin.com/raw/GQreZqPj" name="" title="Demo" />, opened network library
![image](https://github.com/user-attachments/assets/80b23128-ddfe-47a1-b213-465b803beb83)

1 double click on link
AR: Description disappered
![image](https://github.com/user-attachments/assets/cdd8b4ae-ba5b-4b71-8a6b-dc0048a63be5)

ER: Description not diappered

**Comment by iquercorb** [comment]
That is because the repository actually doesn't have description any more, so it update to *nothing*. However this lead me to what is probably the real originating bu, that is, the Repository Editor doesn't save the description string, replacing it by empty string.

fixed in source code.
