### ISSUE TITLE
[Question] What purpose of <icon> in hub.omx?

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#116]
i wondering for what purpose exists this one string in hub.omx?
` <icon>C:\blabla\someapp.exe</icon>`

**Comment by iquercorb** [comment]
It is a relic of old implementation, when it was possible to associate custom icon to Hub to be displayed in the main interface. I removed it from UI, but main pieces of code still here under the hood.

**Comment by lmiol** [comment]
i thout its planned for button PLAY, which start the game
okay, i will remove this from config after test new version
