### ISSUE TITLE
[Suggestion] Icons for Downgrade and Upgrade

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#117]
As i promised here https://github.com/iquercorb/OpenModMan/issues/106

Same color but different ways of arrow
same color telling - its a changing version
arrow point up/down - telling what exactly will happen downgrade or upgrade
![image](https://github.com/user-attachments/assets/409615f9-730b-4d14-b50e-04f843c821fb)

Same icon of double arrows, but different colors Blue - is upgrade and orange downgrade 
same icon - its a changing version
different color - telling what exactly will happen downgrade or upgrade
![image](https://github.com/user-attachments/assets/58a29bcd-78ca-49aa-9df9-34c1ceb22e13)

Second version
![image](https://github.com/user-attachments/assets/be6aa218-2e48-4854-8253-72cd3c582b48)

also on all pictures is little bit resized Pause button dimensions

Red/Orange are always negative actions
Blue/Green are positive ones
 First image looks cool, but we must understand that downgrade is a not a often case. Upgrade is often case. So always to see Orange uparrow is littlebit confuse for user.
So if users all the time will see same icon but with different colors it would more userfriendly. Like this one example
![image](https://github.com/user-attachments/assets/e822566a-666d-4a7d-850e-e1463a789bba)

if you interested - give me source icons -- i will do files what you need

**Comment by lmiol** [comment]
I also consulting with the best friend of mine designer
and he told me for user both icons means the same and user is need to download at both cases.
so for better understanding is better to make same icon for upgrade and for downgrade with same positive color

but in Version colum show some icon or even just text with symbol !
for example
version 1.1.0 (!)
and if you hover will be hint - "Attention! This version is younger than the one you have already downloaded" or kinda

Example (withour orange downngrade icon, only Blue
![image](https://github.com/user-attachments/assets/2f4ca4c4-fb1a-44ad-a130-88e70b3fc212)

**Comment by iquercorb** [comment]
You have misconception about these icons, especially for those informing about "upgrade" or "downgrade". They are **status** icons, it is only here to inform that the Mod already exist locally, but, either the same version, a greater version, or a lower version... so icons cannot "tell what exactly will happen downgrade or upgrade", because this depend on user preference and user choice... 

In the case you download a greater version and if (and only if) user left default parameters or explicitly choose to, this will perform an "upgrade" by deleting the "older" version... There is nothing such as "downgrade" process, if you download an older version, you will simply end with two versions in your local library.

> and he told me for user both icons means the same and user is need to download at both cases.

No, user *need* nothing, user do what he want, user is free ! He decide what he want to do, software is only informs about the state of things, not what to do.

**Comment by lmiol** [comment]
There is no misunderstanding :D
Upon first use, I immediately guessed that these were informational icons. The only thing that confused me was the gray downward arrow, prompting me to hover over it. However, it's not a given that other users are as tech-savvy as I am and will know to hover to see the tooltip (which you seem to have implemented in the code).

My personal experience can explain the downgrade through a user scenario: the new version (upgrade) for some reason turned out to be poor. The most common reason for this is bugs, and fixing the issue in a timely manner isn’t always possible. Consequently, users downgrade to the old version. However, in this scenario, I don't understand why users would want to keep the new bugged version if it is meant to be urgently replaced. If you know of other user scenarios for downgrades, please describe them, because so far the feature of maintaining two versions doesn't make much sense.

To summarize, the designed icons I sent are slightly better than the option with the orange upward arrow, which tends to create a sense of anxiety and reluctance to update, while the gray downward arrow adds some necessity to download it for some reason. It’s not guaranteed that the user will see both icons at the same time and connect the dots that these represent different versions. 

In other words, seeing just the gray icon gives the impression of downloading, while the orange upward arrow seems to indicate an upload in the opposite direction (to server). Therefore, the double arrows, in any form, help clarify this confusion. The two orange arrows I created were more of an option to please you and address the gray upload issue.

For now, since I don’t see any scenarios in my use cases where keeping two versions would be necessary, I will be forced to increment the version and copy the old working version into the new working one. This means I will have to write “version rollback” in the fix notes of the new version, which is a bit wrong according to the general rules of versioning, but at least I will be sure that users will not be left with a defective version.

**Comment by iquercorb** [comment]
I will see to create icons that are less confusing comparing to the "download" icon. I could imagine scenario where user want to keep several versions of the same Mod... And if he don't want, he doesn't download any older version or he delete unwanted versions from its local library. The repository manager also can remove it from its repository to prevent users to accidentally download previous version.

**Comment by iquercorb** [comment]
Changed newer and older versions icons:
![omm_upg_dng_sts_icons](https://github.com/user-attachments/assets/4331ca31-19f7-4163-9640-0f9aac598a9d)

**Comment by lmiol** [comment]
If two versions are retained during a downgrade, users will be left wondering, "When the new version comes out, how will everything work? Will both versions be updated? Or just one? If it's just one, which one will be updated?" 

Maintaining two versions during a downgrade creates extremely convoluted logic that is not intuitive and lacks support from user scenarios. At the very least, you haven't explained why this is necessary for users

**Comment by lmiol** [comment]
cool thing
