### ISSUE TITLE
1.3.1 missed description strings =)

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#119]
https://github.com/iquercorb/OpenModMan/releases/tag/1.3.1

- Added bytes info for Total size of mod [#106](https://github.com/iquercorb/OpenModMan/issues/106)
- Added description tooltip for status icons [#105](https://github.com/iquercorb/OpenModMan/issues/105)
- Renamed mod menu selection to "Open with default program" instead of "Open in Explorer" [#104](https://github.com/iquercorb/OpenModMan/issues/104)
- Fixed bug of fast installed mods [#103](https://github.com/iquercorb/OpenModMan/issues/103)

maybe missed something else also, idk

**Comment by iquercorb** [comment]
It's deliberate, not really a change..
