### ISSUE TITLE
Reliability issues with tracking contents of Local Library folder

### ISSUE THREAD

**Issue by shovas** [iquercorb/OpenModMan#130]
I just had a situation where I toggled a folder and it didn't actually install any files

There's something about OMM and tracking the Local Library when you're also making changes in that folder at the same time which I do because I'm packaging mods or developing in that folder.

What happened was I copy&pasted a folder in windows file manager to make a copy and made some changes to the files inside it. Then I toggled in OMM and it didn't install anything.

There are also times when I zip up a folder and OMM doesn't seem to reliably and robustly catch the change. Sometimes I get an error. Sometimes the zip disappears from the list and if I change channel and come back it's there (alternatively, I'm in the habit of restarting the app when that happens).

![image](https://github.com/user-attachments/assets/015cc15e-69ee-4f96-8fb9-ccaa4ce4e388)

In the screenshot, it was the highlighted folder that I copy&paste to make new versions of. Sometimes OMM catches it and sometimes not.

I think there's just a general robustness and reliability issue with tracking changes in that folder.

**Comment by iquercorb** [comment]
Hard to say what happen exactly without steps to reproduce. However, the fact is that current directory notification (tracking) implementation does not track Mod's sub-trees. More precisely If you add, remove or rename direct any child of a Mod directory, it will detect it, but nothing more, also it will not report any change deeper than direct children of Mod directory (this is how Windows work)... This may explain a least a part of what you experienced.

I will changes the code to enable tracking of subtrees, which will make the thing more robust.

For the rest, Mod disapearing, error message, etc. I cannot debug without specific error and step to reproduce.

**Comment by shovas** [comment]
Thanks for taking a look. I'll try to nail down the case to reproduce.

**Comment by RealDrJester** [comment]
I do not know if this is the same issue, but it seems to be quite similar. If I add a file or delete a file in the mod folder, I will need to restart OOM for it to pick up the file and transfer it to the target directory. 

If I delete the file, while OOM is open, it will refuse to install the mod, throwing an error. It will work once I restart OOM. 

If I add a new mod folder for installation, OOM will act as if it is installed, but no file will be copied. Workaround to this is, once again, restarting OOM. 

Based on what was described by the OP, it seems quite similar to what I am facing, but it could be different issues.

**Comment by iquercorb** [comment]
Adding or deleting **a direct child** (file or folder) of Mod folder should be detected and trigger a Mod tree refresh... This is how it work on my side, can you confirm on your side ? Does your Library folder or Mod folders have specific permission or special property (network folder, for example) ?

**Comment by shovas** [comment]
> Adding or deleting **a direct child** (file or folder) of Mod folder should be detected and trigger a Mod tree refresh... This is how it work on my side, can you confirm on your side ? Does your Library folder or Mod folders have specific permission or special property (network folder, for example) ?

I believe this case works.

And, per your description of how it it supposed to work, a file rename in a subfolder is not caught (in my case there were no overwritten files but OMM still reported it would overwrite another mod).

**Comment by iquercorb** [comment]
> And, per your description of how it it supposed to work, a file rename in a subfolder

Yes, the current implementation does not detect changes in subtrees. Only changes of Mod folder's direct child content are reported. This mean if you have a Mod folder and add, remove, or rename an item directly in this folder, it is reported as a modification of the Mod Folder (this is how Windows notifycation work), but, if you have subfolder and make some modification inside, this is not reported, so the Mod content is not reloaded and OMM still "think" it is unchanged.

The modification to detect changes in subtree is already done in source code, this will be available in the next release.

**Comment by shovas** [comment]
Here's another case I've had in the past I just repeated now:

1. Uninstall existing installed ZIP package in folder
2. Unzip ZIP in same folder
3. Make a change in some subfolder (I don't think this matters though0
4. Re-zip folder to same name ZIP
5. ZIP can disappear from Local Library pane (it doesn't always happen like this though)

This might have to do with 7zip being configured to use temporary files in the same folder so maybe OMM is detecting two changes in quick succession and something is going on there.

**Comment by iquercorb** [comment]
Ok so, for the disappearing Zip file, I found the cause of the issue, and this is indeed because of multiple notifications that come at once and thread timing/latency side effects. 

I modified the implementation of directory changes notification engine, now tracking subtree item, and properly handle concurrent or short-time contradictory notifications. I also forced Mods to refresh content before any installation, thing that should have been from the beginning.

The next version should be properly robust for comfortable Mods editing without glitches nor inconsistency. Previous implementation was indeed a bit to "lazy"

**Comment by shovas** [comment]
Sounds great, thanks for the fixes!

**Comment by RealDrJester** [comment]
Thank you for thew work and the fixes! :) 

I love OMM!

**Comment by shovas** [comment]
The irl case I keep tripping over, because a mod author keeps releasing new versions, worked first time in 1.3.2. So nice to have that working. Thank you! :)
