### ISSUE TITLE
[Issue] Window sizes, column header width, and selected hubs/channels are not stored upon closing OMM.

### ISSUE THREAD

**Issue by OR-WS** [iquercorb/OpenModMan#132]
Per the title. Every time OMM is started, the window and layout is reset to the defaults.

**Comment by iquercorb** [comment]
For window size and inner layout : This should work, if it doesn't work, this mean the config.xml is not readable or writable.
For List-view column headers sizes, they are indeed not saved it is not implemented.
For default selected Hub you must configure Hub to be loaded at startup (Edit > Manager Options...) :
  - check "Open Mod Hub at startup"
  - Open and select desired Hub files
  - The last one in the list is the one that is automatically selected
