### ISSUE TITLE
[BUG] Weird resize side effect on dropdown menu

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#97]
Precondition: already added repo with mods
1 open tab Network Library
2 resize Repo block at any distance
3 right click on any mod as a resulr
AR:  cursor changed to Resize 
![image](https://github.com/iquercorb/OpenModMan/assets/264879/c65ac5db-62e9-4e3e-a1ee-05e746f38ff1)
ER: cursor will be same Default

App version 1.2.9

**Comment by iquercorb** [comment]
Problem already solved in source code since last release, will be corrected in the next
