### ISSUE TITLE
[BUG] Download doesn't work

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#98]
Precondition: Already added Repo, atleast 1 mod not downloaded before
1 open tab Network Library
2 click on mod which not downloaded before
3 double click or click button Download
AR: Nothing happens
ER: starting download

app version 1.2.9

**Comment by iquercorb** [comment]
I am not able to reproduce. What do you mean by "atleast 1 mod not downloaded before" ? What is the status icon (left most column) of the Mod ? Do you have any output in the debug log ?

**Comment by lmiol** [comment]
> I am not able to reproduce. What do you mean by "atleast 1 mod not downloaded before" ? What is the status icon (left most column) of the Mod ? Do you have any output in the debug log ?

bad investigation, i still looking to correct steps. write you later

**Comment by lmiol** [comment]
i think it should be closed because i cant find out right steps, its floating
