### ISSUE TITLE
[Suggestion] Checkmark color correction

### ISSUE THREAD

**Issue by lmiol** [iquercorb/OpenModMan#99]
about the issue https://github.com/iquercorb/OpenModMan/issues/87
you did reverse logic for color
i mean now Blue checkmark means the same as Package dependency icon - it's same doubled logic
![image](https://github.com/iquercorb/OpenModMan/assets/264879/cf15adda-8b0b-436d-9030-651a26bd2ab7)

how i think it should be
![image](https://github.com/iquercorb/OpenModMan/assets/264879/cac89fe5-dde2-4354-9b9a-1af4fc3b4809)
and if i delete  dependent  **King's Pass - Castle HEADS** -- blue checkmark of dependency **King's Pass - Castle** becomes green
![image](https://github.com/iquercorb/OpenModMan/assets/264879/4f8b4b5b-0bb7-4902-b74f-908932623ee5)

its becomes green because now its not is dependency but just a mod

and also if i install a again **King's Pass - Castle HEADS** then -- green checkmark f dependency **King's Pass - Castle** becomes blue

i mean atleast after this correction point of blue checkmark would be right logic without cross logic of package icon

**Comment by iquercorb** [comment]
You right, blue check is currently more redundant indication, I changed the logic in source code. This will be available in the next release.
